name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Add build steps here if needed (e.g., npm build, jekyll, etc.)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './'  # Path to your built static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
